services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html 
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      REDIS_SCHEME: ${REDIS_SCHEME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8000:80"

  invoice-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.worker
    volumes:
      - .:/var/www
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      REDIS_SCHEME: ${REDIS_SCHEME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_BRPOP_TIMEOUT: ${REDIS_BRPOP_TIMEOUT}
      REDIS_QUEUE_NAME: 'queue_invoice'
    depends_on:
      - redis
      - mongo

  email-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.worker
    volumes:
      - .:/var/www
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      REDIS_SCHEME: ${REDIS_SCHEME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_BRPOP_TIMEOUT: ${REDIS_BRPOP_TIMEOUT}
      REDIS_QUEUE_NAME: 'queue_email'
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"